/**
 * Ambalaj Tipleri — UN Recommendation 21 (Fransız Gümrük referansı).
 * 377 standart kod, kategorize edilmiş ve Türkçeye çevrilmiş.
 */

export type PackageCategory = 'bag' | 'box' | 'crate' | 'pallet' | 'ibc' | 'drum' | 'bottle' | 'tube' | 'jerrican' | 'container' | 'bulk' | 'reel' | 'piece' | 'other'

export interface PackageTypeInfo {
  code: string
  tr: string
  fr: string
  category: PackageCategory
}

export const PACKAGE_CATEGORY_LABELS: Record<PackageCategory, string> = {
  pallet: "Palet",
  ibc: "IBC / Big Bag",
  bag: "Çuval / Torba",
  drum: "Varil / Fıçı",
  crate: "Sandık / Kasa",
  box: "Kutu / Karton",
  bottle: "Şişe / Flakon",
  tube: "Tüp",
  jerrican: "Bidon / Jerrican",
  container: "Konteyner",
  bulk: "Dökme",
  reel: "Bobin / Rulo",
  piece: "Levha / Çubuk / Parça",
  other: "Diğer",
}

export const PACKAGE_TYPES: PackageTypeInfo[] = [
  { code: "44", tr: "Polibag (PE Torba)", fr: "Sac de polyéthylène («polybag»)", category: 'bag' },
  { code: "5H", tr: "Plastik Dokuma Çuval", fr: "Sac en tissu de plastique", category: 'bag' },
  { code: "5L", tr: "Tekstil Çuval", fr: "Sac en textile", category: 'bag' },
  { code: "5M", tr: "Kağıt Torba", fr: "Sac en papier", category: 'bag' },
  { code: "BG", tr: "Çuval (bag)", fr: "Sac (bag)", category: 'bag' },
  { code: "EC", tr: "Çuval plastique", fr: "Sac plastique", category: 'bag' },
  { code: "FX", tr: "Çuval, contenant Esnek", fr: "Sac, contenant souple", category: 'bag' },
  { code: "GY", tr: "Çuval de jute/toile («gunny bag»)", fr: "Sac de jute/toile («gunny bag»)", category: 'bag' },
  { code: "JB", tr: "Çuval «jumbo»", fr: "Sac «jumbo»", category: 'bag' },
  { code: "JT", tr: "Jüt Çuval", fr: "Sac en jute", category: 'bag' },
  { code: "MB", tr: "Çok Katlı Torba", fr: "Sac multiplis", category: 'bag' },
  { code: "MS", tr: "Çuval multicorde", fr: "Sac multicorde", category: 'bag' },
  { code: "PO", tr: "Çuvalhet (pouch)", fr: "Sachet (pouch)", category: 'bag' },
  { code: "SA", tr: "Çuval (sack)", fr: "Sac (sack)", category: 'bag' },
  { code: "SH", tr: "Çuvalhet (sachet)", fr: "Sachet (sachet)", category: 'bag' },
  { code: "TT", tr: "Çuval de manutention («tote»)", fr: "Sac de manutention («tote»)", category: 'bag' },
  { code: "XA", tr: "Plastik Dokuma Çuval, sans revêtement intérieur ni doublure", fr: "Sac en tissu de plastique, sans revêtement intérieur ni doublure", category: 'bag' },
  { code: "XB", tr: "Plastik Dokuma Çuval, étanche aux pulvérulents", fr: "Sac en tissu de plastique, étanche aux pulvérulents", category: 'bag' },
  { code: "XC", tr: "Plastik Dokuma Çuval, résistant à l'eau", fr: "Sac en tissu de plastique, résistant à l'eau", category: 'bag' },
  { code: "XD", tr: "Çuval en film de plastique", fr: "Sac en film de plastique", category: 'bag' },
  { code: "XF", tr: "Tekstil Çuval, sans revêtement intérieur ni doublure", fr: "Sac en textile, sans revêtement intérieur ni doublure", category: 'bag' },
  { code: "XG", tr: "Tekstil Çuval, étanche aux pulvérulents", fr: "Sac en textile, étanche aux pulvérulents", category: 'bag' },
  { code: "XH", tr: "Tekstil Çuval, résistant à l'eau", fr: "Sac en textile, résistant à l'eau", category: 'bag' },
  { code: "XJ", tr: "Kağıt Torba çok katlı", fr: "Sac en papier multiplis", category: 'bag' },
  { code: "XK", tr: "Kağıt Torba çok katlı, résistant à l'eau", fr: "Sac en papier multiplis, résistant à l'eau", category: 'bag' },
  { code: "ZB", tr: "Çuval de grande taille", fr: "Sac de grande taille", category: 'bag' },
  { code: "AB", tr: "Karton Kap", fr: "Réceptacle en carton", category: 'box' },
  { code: "BX", tr: "Kutu (box)", fr: "Boîte (box)", category: 'box' },
  { code: "CS", tr: "Kutu (case)", fr: "Boîte (case)", category: 'box' },
  { code: "CT", tr: "Karton", fr: "Carton", category: 'box' },
  { code: "DK", tr: "Karton pour vrac", fr: "Carton pour vrac", category: 'box' },
  { code: "DV", tr: "Tepsi Kartondan, Tek Kat, Kapaksız", fr: "Plateau en carton, un niveau, sans couvercle", category: 'box' },
  { code: "DY", tr: "Tepsi Kartondan, Çift Kat, Kapaksız", fr: "Plateau en carton, deux niveaux, sans couvercle", category: 'box' },
  { code: "HC", tr: "Kulplu Sepet, Karton", fr: "Corbeille avec anse, en carton", category: 'box' },
  { code: "IB", tr: "Sunum Ambalajı, Karton", fr: "Emballage de présentation, en carton", category: 'box' },
  { code: "IK", tr: "Karton Ambalaj, Tutma Delikli", fr: "Emballage en carton, avec trous de préhension", category: 'box' },
  { code: "KI", tr: "Kutu à outils (kit)", fr: "Boîte à outils (kit)", category: 'box' },
  { code: "MX", tr: "Kutu d'allumettes", fr: "Boîte d'allumettes", category: 'box' },
  { code: "NS", tr: "Kutus gigognes", fr: "Boîtes gigognes", category: 'box' },
  { code: "TN", tr: "Teneke Kutu", fr: "Boîte en fer-blanc", category: 'box' },
  { code: "4A", tr: "Çelik Sandık", fr: "Caisse en acier", category: 'crate' },
  { code: "4B", tr: "Alüminyum Sandık", fr: "Caisse en aluminium", category: 'crate' },
  { code: "4C", tr: "Doğal Ahşap Sandık", fr: "Caisse en bois naturel", category: 'crate' },
  { code: "4D", tr: "Kontraplak Sandık", fr: "Caisse en contreplaqué", category: 'crate' },
  { code: "4F", tr: "Yeniden İşlenmiş Ahşap Sandık", fr: "Caisse en bois reconstitué", category: 'crate' },
  { code: "4G", tr: "Lifli Levha Sandık", fr: "Caisse en panneaux de fibres", category: 'crate' },
  { code: "4H", tr: "Plastik Sandık", fr: "Caisse en plastique", category: 'crate' },
  { code: "7A", tr: "Sandık, voiture (case, car)", fr: "Caisse, voiture (case, car)", category: 'crate' },
  { code: "7B", tr: "Tahta Sandık", fr: "Caisse en bois", category: 'crate' },
  { code: "8B", tr: "Kasalı Kafes Ahşaptan", fr: "Casier en bois", category: 'crate' },
  { code: "BC", tr: "Kasalı Kafes à bouteilles", fr: "Casier à bouteilles", category: 'crate' },
  { code: "BW", tr: "Sandık pour liquides", fr: "Caisse pour liquides", category: 'crate' },
  { code: "CB", tr: "Kasalı Kafes à bière", fr: "Casier à bière", category: 'crate' },
  { code: "DA", tr: "Kasalı Kafes Plastikten, à plusieurs niveaux", fr: "Casier en plastique, à plusieurs niveaux", category: 'crate' },
  { code: "DB", tr: "Kasalı Kafes Ahşaptan, à plusieurs niveaux", fr: "Casier en bois, à plusieurs niveaux", category: 'crate' },
  { code: "DC", tr: "Karton Sandık, à plusieurs niveaux", fr: "Caisse en carton, à plusieurs niveaux", category: 'crate' },
  { code: "DH", tr: "Sandık CHEP (Commonwealth Handling Equipment Pool), Eurobox", fr: "Caisse CHEP (Commonwealth Handling Equipment Pool), Eurobox", category: 'crate' },
  { code: "DL", tr: "Kasalı Kafes Plastikten pour vrac", fr: "Casier en plastique pour vrac", category: 'crate' },
  { code: "DM", tr: "Kasalı Kafes Ahşaptan pour vrac", fr: "Casier en bois pour vrac", category: 'crate' },
  { code: "ED", tr: "Sandık pallette", fr: "Caisse pallette", category: 'crate' },
  { code: "EE", tr: "Sandık pallette Ahşaptan", fr: "Caisse pallette en bois", category: 'crate' },
  { code: "EF", tr: "Sandık pallette Kartondan", fr: "Caisse pallette en carton", category: 'crate' },
  { code: "EG", tr: "Sandık pallette Plastikten", fr: "Caisse pallette en plastique", category: 'crate' },
  { code: "EH", tr: "Sandık pallette Metalden", fr: "Caisse pallette en métal", category: 'crate' },
  { code: "FC", tr: "Kafes Kasası", fr: "Cageot", category: 'crate' },
  { code: "MA", tr: "Kasalı Kafes Metalden", fr: "Casier en métal", category: 'crate' },
  { code: "MC", tr: "Kasalı Kafes à lait", fr: "Casier à lait", category: 'crate' },
  { code: "QP", tr: "Doğal Ahşap Sandık, ordinaire", fr: "Caisse en bois naturel, ordinaire", category: 'crate' },
  { code: "QQ", tr: "Doğal Ahşap Sandık, à panneaux étanches aux pulvérulents", fr: "Caisse en bois naturel, à panneaux étanches aux pulvérulents", category: 'crate' },
  { code: "QR", tr: "Plastik Sandık expansé", fr: "Caisse en plastique expansé", category: 'crate' },
  { code: "QS", tr: "Plastik Sandık Sert", fr: "Caisse en plastique rigide", category: 'crate' },
  { code: "SC", tr: "Küçük Kasa (shallow crate)", fr: "Cagette (shallow crate)", category: 'crate' },
  { code: "SK", tr: "Küçük Kasa (tray pack)", fr: "Cagette (tray pack)", category: 'crate' },
  { code: "TC", tr: "Sandık à thé", fr: "Caisse à thé", category: 'crate' },
  { code: "YB", tr: "Kompozit Ambalaj, Plastik Kap ile caisse extérieure Çelikten", fr: "Emballage composite, récipient en plastique avec caisse extérieure en acier", category: 'crate' },
  { code: "YD", tr: "Kompozit Ambalaj, Plastik Kap ile caisse extérieure Alüminyumdan", fr: "Emballage composite, récipient en plastique avec caisse extérieure en aluminium", category: 'crate' },
  { code: "YF", tr: "Kompozit Ambalaj, Plastik Kap ile caisse extérieure Ahşaptan", fr: "Emballage composite, récipient en plastique avec caisse extérieure en bois", category: 'crate' },
  { code: "YH", tr: "Kompozit Ambalaj, Plastik Kap ile caisse extérieure Kontraplaktan", fr: "Emballage composite, récipient en plastique avec caisse extérieure en contre-plaqué", category: 'crate' },
  { code: "YK", tr: "Kompozit Ambalaj, Plastik Kap ile caisse extérieure Kartondan", fr: "Emballage composite, récipient en plastique avec caisse extérieure en carton", category: 'crate' },
  { code: "YM", tr: "Kompozit Ambalaj, Plastik Kap ile caisse extérieure Sert Plastikten", fr: "Emballage composite, récipient en plastique avec caisse extérieure en plastique rigide", category: 'crate' },
  { code: "YP", tr: "Kompozit Ambalaj, Cam Kap ile caisse extérieure Çelikten", fr: "Emballage composite, récipient en verre avec caisse extérieure en acier", category: 'crate' },
  { code: "YR", tr: "Kompozit Ambalaj, Cam Kap ile caisse extérieure Alüminyumdan", fr: "Emballage composite, récipient en verre avec caisse extérieure en aluminium", category: 'crate' },
  { code: "YS", tr: "Kompozit Ambalaj, Cam Kap ile caisse extérieure Ahşaptan", fr: "Emballage composite, récipient en verre avec caisse extérieure en bois", category: 'crate' },
  { code: "YX", tr: "Kompozit Ambalaj, Cam Kap ile caisse extérieure Kartondan", fr: "Emballage composite, récipient en verre avec caisse extérieure en carton", category: 'crate' },
  { code: "8A", tr: "Tahta Palet", fr: "Palette en bois", category: 'pallet' },
  { code: "AF", tr: "Palet modulaire, rehausses de dimensions 80 x 60 cm", fr: "Palette modulaire, rehausses de dimensions 80 x 60 cm", category: 'pallet' },
  { code: "AH", tr: "Palet, 100 x 110 cm", fr: "Palette, 100 x 110 cm", category: 'pallet' },
  { code: "OA", tr: "Palet CHEP (Commonwealth Handling Equipment Pool) 40  x 60  cm", fr: "Palette CHEP (Commonwealth Handling Equipment Pool) 40  x 60  cm", category: 'pallet' },
  { code: "OB", tr: "Palet CHEP (Commonwealth Handling Equipment Pool) 80  x 120  cm", fr: "Palette CHEP (Commonwealth Handling Equipment Pool) 80  x 120  cm", category: 'pallet' },
  { code: "OC", tr: "Palet CHEP (Commonwealth Handling Equipment Pool)100  x 120  cm", fr: "Palette CHEP (Commonwealth Handling Equipment Pool)100  x 120  cm", category: 'pallet' },
  { code: "OD", tr: "Palet, AS 4068-1993", fr: "Palette, AS 4068-1993", category: 'pallet' },
  { code: "OE", tr: "Palet ISO T11", fr: "Palette ISO T11", category: 'pallet' },
  { code: "PB", tr: "Palet-caisse (pallet box)", fr: "Palette-caisse (pallet box)", category: 'pallet' },
  { code: "PD", tr: "Palet modulaire, rehausses de dimensions 80 x 100 cm", fr: "Palette modulaire, rehausses de dimensions 80 x 100 cm", category: 'pallet' },
  { code: "PE", tr: "Palet modulaire, rehausses de dimensions 80 x 120 cm", fr: "Palette modulaire, rehausses de dimensions 80 x 120 cm", category: 'pallet' },
  { code: "PX", tr: "Palet", fr: "Palette", category: 'pallet' },
  { code: "SL", tr: "Feuille-palette", fr: "Feuille-palette", category: 'pallet' },
  { code: "TW", tr: "Palet Kartondan ondulé lourd («tri-wall»)", fr: "Palette en carton ondulé lourd («tri-wall»)", category: 'pallet' },
  { code: "43", tr: "Esnek IBC (Big Bag) (big bag)", fr: "Grand récipient pour vrac souple (big bag)", category: 'ibc' },
  { code: "AA", tr: "IBC Konteyner, Sert Plastikten", fr: "Grand récipient pour vrac, en plastique rigide", category: 'ibc' },
  { code: "WA", tr: "IBC Konteyner", fr: "Grand récipient pour vrac", category: 'ibc' },
  { code: "WC", tr: "IBC Konteyner, Çelikten", fr: "Grand récipient pour vrac, en acier", category: 'ibc' },
  { code: "WD", tr: "IBC Konteyner, Alüminyumdan", fr: "Grand récipient pour vrac, en aluminium", category: 'ibc' },
  { code: "WF", tr: "IBC Konteyner, métallique", fr: "Grand récipient pour vrac, métallique", category: 'ibc' },
  { code: "WG", tr: "IBC Konteyner, Çelikten, ile remplissage ou vidange sous pression supérieure à 10 kpa (0,1 bar)", fr: "Grand récipient pour vrac, en acier, avec remplissage ou vidange sous pression supérieure à 10 kpa (0,1 bar)", category: 'ibc' },
  { code: "WH", tr: "IBC Konteyner, Alüminyumdan, ile remplissage ou vidange sous pression supérieure à 10 kpa (0,1 bar)", fr: "Grand récipient pour vrac, en aluminium, avec remplissage ou vidange sous pression supérieure à 10 kpa (0,1 bar)", category: 'ibc' },
  { code: "WJ", tr: "IBC Konteyner, métallique, pour remplissage ou vidange sous pression supérieure à 10 kpa (0,1 bar)", fr: "Grand récipient pour vrac, métallique, pour remplissage ou vidange sous pression supérieure à 10 kpa (0,1 bar)", category: 'ibc' },
  { code: "WK", tr: "Sıvı IBC, Çelikten", fr: "Grand récipient pour vrac liquide, en acier", category: 'ibc' },
  { code: "WL", tr: "Sıvı IBC, Alüminyumdan", fr: "Grand récipient pour vrac liquide, en aluminium", category: 'ibc' },
  { code: "WM", tr: "Sıvı IBC, métallique", fr: "Grand récipient pour vrac liquide, métallique", category: 'ibc' },
  { code: "WN", tr: "IBC Konteyner, en tissu de plastique, sans revêtement intérieur ni doublure", fr: "Grand récipient pour vrac, en tissu de plastique, sans revêtement intérieur ni doublure", category: 'ibc' },
  { code: "WP", tr: "IBC Konteyner, en tissu de plastique, ile revêtement intérieur", fr: "Grand récipient pour vrac, en tissu de plastique, avec revêtement intérieur", category: 'ibc' },
  { code: "WQ", tr: "IBC Konteyner, en tissu de plastique, ile doublure", fr: "Grand récipient pour vrac, en tissu de plastique, avec doublure", category: 'ibc' },
  { code: "WR", tr: "IBC Konteyner, en tissu de plastique, ile revêtement intérieur et doublure", fr: "Grand récipient pour vrac, en tissu de plastique, avec revêtement intérieur et doublure", category: 'ibc' },
  { code: "WS", tr: "IBC Konteyner, en film de plastique", fr: "Grand récipient pour vrac, en film de plastique", category: 'ibc' },
  { code: "WT", tr: "IBC Konteyner, en textile sans revêtement intérieur ni doublure", fr: "Grand récipient pour vrac, en textile sans revêtement intérieur ni doublure", category: 'ibc' },
  { code: "WU", tr: "IBC Konteyner, Doğal Ahşaptan, ile doublure", fr: "Grand récipient pour vrac, en bois naturel, avec doublure", category: 'ibc' },
  { code: "WV", tr: "IBC Konteyner, en textile, ile revêtement intérieur", fr: "Grand récipient pour vrac, en textile, avec revêtement intérieur", category: 'ibc' },
  { code: "WW", tr: "IBC Konteyner, en textile, ile doublure", fr: "Grand récipient pour vrac, en textile, avec doublure", category: 'ibc' },
  { code: "WX", tr: "IBC Konteyner, en textile, ile revêtement intérieur et doublure", fr: "Grand récipient pour vrac, en textile, avec revêtement intérieur et doublure", category: 'ibc' },
  { code: "WY", tr: "IBC Konteyner, Kontraplaktan, ile doublure", fr: "Grand récipient pour vrac, en contre-plaqué, avec doublure", category: 'ibc' },
  { code: "WZ", tr: "IBC Konteyner, Yeniden İşlenmiş Ahşaptan, ile doublure", fr: "Grand récipient pour vrac, en bois reconstitué, avec doublure", category: 'ibc' },
  { code: "ZA", tr: "IBC Konteyner, Kağıttan çok katlı", fr: "Grand récipient pour vrac, en papier multiplis", category: 'ibc' },
  { code: "ZC", tr: "IBC Konteyner, Kağıttan çok katlı, résistant à l'eau", fr: "Grand récipient pour vrac, en papier multiplis, résistant à l'eau", category: 'ibc' },
  { code: "ZD", tr: "IBC Konteyner solide, Sert Plastikten, ile équipement de structure", fr: "Grand récipient pour vrac solide, en plastique rigide, avec équipement de structure", category: 'ibc' },
  { code: "ZF", tr: "IBC Konteyner solide, Sert Plastikten, autoportant", fr: "Grand récipient pour vrac solide, en plastique rigide, autoportant", category: 'ibc' },
  { code: "ZG", tr: "IBC Konteyner, Sert Plastikten, ile équipement de structure, pour remplissage ou vidange sous pression", fr: "Grand récipient pour vrac, en plastique rigide, avec équipement de structure, pour remplissage ou vidange sous pression", category: 'ibc' },
  { code: "ZH", tr: "IBC Konteyner , Sert Plastikten, autoportant, pour remplissage ou vidange sous pression", fr: "Grand récipient pour vrac , en plastique rigide, autoportant, pour remplissage ou vidange sous pression", category: 'ibc' },
  { code: "ZJ", tr: "Sıvı IBC, Sert Plastikten, ile équipement de structure", fr: "Grand récipient pour vrac liquide, en plastique rigide, avec équipement de structure", category: 'ibc' },
  { code: "ZK", tr: "Sıvı IBC, Sert Plastikten, autoportant", fr: "Grand récipient pour vrac liquide, en plastique rigide, autoportant", category: 'ibc' },
  { code: "ZM", tr: "IBC Konteyner solide, en matériau composite, ile récipient intérieur Esnek Plastikten", fr: "Grand récipient pour vrac solide, en matériau composite, avec récipient intérieur en plastique souple", category: 'ibc' },
  { code: "ZN", tr: "IBC, Kompozit, Sert Plastik İç Kapla, pour remplissage ou vidange sous pression", fr: "Grand récipient pour vrac, en matériau composite, avec récipient intérieur en plastique rigide, pour remplissage ou vidange sous pression", category: 'ibc' },
  { code: "ZP", tr: "IBC, Kompozit, Esnek Plastik İç Kapla, pour remplissage ou vidange sous pression", fr: "Grand récipient pour vrac, en matériau composite, avec récipient intérieur en plastique souple, pour remplissage ou vidange sous pression", category: 'ibc' },
  { code: "ZQ", tr: "Sıvı IBC, Kompozit, Sert Plastik İç Kapla", fr: "Grand récipient pour vrac liquide, en matériau composite, avec récipient intérieur en plastique rigide", category: 'ibc' },
  { code: "ZR", tr: "Sıvı IBC, Kompozit, Esnek Plastik İç Kapla", fr: "Grand récipient pour vrac liquide, en matériau composite, avec récipient intérieur en plastique souple", category: 'ibc' },
  { code: "ZS", tr: "IBC Konteyner, en matériaux composites", fr: "Grand récipient pour vrac, en matériaux composites", category: 'ibc' },
  { code: "ZT", tr: "IBC Konteyner, Lifli Levhadan", fr: "Grand récipient pour vrac, en panneaux de fibres", category: 'ibc' },
  { code: "ZU", tr: "IBC Konteyner, Esnek", fr: "Grand récipient pour vrac, souple", category: 'ibc' },
  { code: "ZV", tr: "IBC Konteyner, Çelik Dışı Metalden", fr: "Grand récipient pour vrac, en métal autre que l'acier", category: 'ibc' },
  { code: "ZW", tr: "IBC Konteyner, Doğal Ahşaptan", fr: "Grand récipient pour vrac, en bois naturel", category: 'ibc' },
  { code: "ZX", tr: "IBC Konteyner, Kontraplaktan", fr: "Grand récipient pour vrac, en contre-plaqué", category: 'ibc' },
  { code: "ZY", tr: "IBC Konteyner, Yeniden İşlenmiş Ahşaptan", fr: "Grand récipient pour vrac, en bois reconstitué", category: 'ibc' },
  { code: "1A", tr: "Çelik Varil", fr: "Fût en acier", category: 'drum' },
  { code: "1B", tr: "Alüminyum Varil", fr: "Fût en aluminium", category: 'drum' },
  { code: "1D", tr: "Kontraplak Varil", fr: "Fût en contre-plaqué", category: 'drum' },
  { code: "1G", tr: "Karton Varil", fr: "Fût en carton", category: 'drum' },
  { code: "1W", tr: "Tahta Varil", fr: "Fût en bois", category: 'drum' },
  { code: "2C", tr: "Ahşap Fıçı", fr: "Tonneau en bois", category: 'drum' },
  { code: "DI", tr: "Varil en fer", fr: "Fût en fer", category: 'drum' },
  { code: "DR", tr: "Varil", fr: "Fût", category: 'drum' },
  { code: "HG", tr: "Fıçı", fr: "Tonneau", category: 'drum' },
  { code: "IH", tr: "Plastik Varil", fr: "Fût en plastique", category: 'drum' },
  { code: "QA", tr: "Çelik Varil, à dessus non amovible", fr: "Fût en acier, à dessus non amovible", category: 'drum' },
  { code: "QB", tr: "Çelik Varil, à dessus amovible", fr: "Fût en acier, à dessus amovible", category: 'drum' },
  { code: "QC", tr: "Alüminyum Varil, à dessus non amovible", fr: "Fût en aluminium, à dessus non amovible", category: 'drum' },
  { code: "QD", tr: "Alüminyum Varil, à dessus amovible", fr: "Fût en aluminium, à dessus amovible", category: 'drum' },
  { code: "QF", tr: "Plastik Varil, à dessus non amovible", fr: "Fût en plastique, à dessus non amovible", category: 'drum' },
  { code: "QG", tr: "Plastik Varil, à dessus amovible", fr: "Fût en plastique, à dessus amovible", category: 'drum' },
  { code: "QH", tr: "Ahşap Fıçı, à bonde", fr: "Tonneau en bois, à bonde", category: 'drum' },
  { code: "QJ", tr: "Ahşap Fıçı, à dessus amovible", fr: "Tonneau en bois, à dessus amovible", category: 'drum' },
  { code: "YA", tr: "Kompozit Ambalaj, Plastik Kap ile fût extérieur Çelikten", fr: "Emballage composite, récipient en plastique avec fût extérieur en acier", category: 'drum' },
  { code: "YC", tr: "Kompozit Ambalaj, Plastik Kap ile fût extérieur Alüminyumdan", fr: "Emballage composite, récipient en plastique avec fût extérieur en aluminium", category: 'drum' },
  { code: "YG", tr: "Kompozit Ambalaj, Plastik Kap ile fût extérieur Kontraplaktan", fr: "Emballage composite, récipient en plastique avec fût extérieur en contre-plaqué", category: 'drum' },
  { code: "YJ", tr: "Kompozit Ambalaj, Plastik Kap ile fût extérieur Kartondan", fr: "Emballage composite, récipient en plastique avec fût extérieur en carton", category: 'drum' },
  { code: "YL", tr: "Kompozit Ambalaj, Plastik Kap ile fût extérieur Plastikten", fr: "Emballage composite, récipient en plastique avec fût extérieur en plastique", category: 'drum' },
  { code: "YN", tr: "Kompozit Ambalaj, Cam Kap ile fût extérieur Çelikten", fr: "Emballage composite, récipient en verre avec fût extérieur en acier", category: 'drum' },
  { code: "YQ", tr: "Kompozit Ambalaj, Cam Kap ile fût extérieur Alüminyumdan", fr: "Emballage composite, récipient en verre avec fût extérieur en aluminium", category: 'drum' },
  { code: "YT", tr: "Kompozit Ambalaj, Cam Kap ile fût extérieur Kontraplaktan", fr: "Emballage composite, récipient en verre avec fût extérieur en contre-plaqué", category: 'drum' },
  { code: "YW", tr: "Kompozit Ambalaj, Cam Kap ile fût extérieur Kartondan", fr: "Emballage composite, récipient en verre avec fût extérieur en carton", category: 'drum' },
  { code: "BO", tr: "Şişe non protégée, silindirik", fr: "Bouteille non protégée, cylindrique", category: 'bottle' },
  { code: "BQ", tr: "Şişe protégée, silindirik", fr: "Bouteille protégée, cylindrique", category: 'bottle' },
  { code: "BS", tr: "Şişe non protégée, bulbeuse", fr: "Bouteille non protégée, bulbeuse", category: 'bottle' },
  { code: "BV", tr: "Şişe protégée, bulbeuse", fr: "Bouteille protégée, bulbeuse", category: 'bottle' },
  { code: "FL", tr: "Flakon", fr: "Flacon", category: 'bottle' },
  { code: "GB", tr: "Şişe à gaz", fr: "Bouteille à gaz", category: 'bottle' },
  { code: "PT", tr: "Saksı, Kavanoz", fr: "Pot, Bocal", category: 'bottle' },
  { code: "TD", tr: "Tüp déformable (collapsible tube)", fr: "Tube déformable (collapsible tube)", category: 'tube' },
  { code: "TU", tr: "Tüp", fr: "Tube", category: 'tube' },
  { code: "TV", tr: "Tüp à embout", fr: "Tube à embout", category: 'tube' },
  { code: "TZ", tr: "Demet Halinde Tüp", fr: "Tubes en ballot, botte, faisceau", category: 'tube' },
  { code: "3A", tr: "Çelik Bidon", fr: "Jerricane en acier", category: 'jerrican' },
  { code: "3H", tr: "Plastik Bidon", fr: "Jerricane en plastique", category: 'jerrican' },
  { code: "CA", tr: "Dörtgen Bidon", fr: "Bidon rectangulaire", category: 'jerrican' },
  { code: "CC", tr: "Süt Bidonu", fr: "Bidon à lait", category: 'jerrican' },
  { code: "CD", tr: "Kulplu ve Ağızlı Bidon", fr: "Bidon avec anse et bec verseur", category: 'jerrican' },
  { code: "CI", tr: "Bidon", fr: "Bidon", category: 'jerrican' },
  { code: "CX", tr: "Silindirik Bidon", fr: "Bidon cylindrique", category: 'jerrican' },
  { code: "JC", tr: "Dörtgen Bidon", fr: "Jerricane rectangulaire", category: 'jerrican' },
  { code: "JY", tr: "Silindirik Bidon", fr: "Jerricane cylindrique", category: 'jerrican' },
  { code: "QK", tr: "Çelik Bidon, à dessus non amovible", fr: "Jerricane en acier, à dessus non amovible", category: 'jerrican' },
  { code: "QL", tr: "Çelik Bidon, à dessus amovible", fr: "Jerricane en acier, à dessus amovible", category: 'jerrican' },
  { code: "QM", tr: "Plastik Bidon, à dessus non amovible", fr: "Jerricane en plastique, à dessus non amovible", category: 'jerrican' },
  { code: "QN", tr: "Plastik Bidon, à dessus amovible", fr: "Jerricane en plastique, à dessus amovible", category: 'jerrican' },
  { code: "1F", tr: "Esnek Konteyner (Big Bag)", fr: "Conteneur souple", category: 'container' },
  { code: "CN", tr: "Konteyner, sans autre précision qu'équipement de transport", fr: "Conteneur, sans autre précision qu'équipement de transport", category: 'container' },
  { code: "GL", tr: "Konteyner, gallon", fr: "Conteneur, gallon", category: 'container' },
  { code: "ME", tr: "Konteyner métallique", fr: "Conteneur métallique", category: 'container' },
  { code: "OU", tr: "Konteyner extérieur", fr: "Conteneur extérieur", category: 'container' },
  { code: "TG", tr: "Konteyner-citerne, générique", fr: "Conteneur-citerne, générique", category: 'container' },
  { code: "VG", tr: "Dökme, gaz (à 1 031 mbar et 15 degré C)", fr: "Vrac, gaz (à 1 031 mbar et 15 degré C)", category: 'bulk' },
  { code: "VL", tr: "Dökme, liquide", fr: "Vrac, liquide", category: 'bulk' },
  { code: "VO", tr: "Dökme, solide, İri Tane (nodules)", fr: "Vrac, solide, particules grosses (nodules)", category: 'bulk' },
  { code: "VQ", tr: "Dökme, gaz liquéfié (à température et pression anormales)", fr: "Vrac, gaz liquéfié (à température et pression anormales)", category: 'bulk' },
  { code: "VR", tr: "Dökme, solide, Granül Tane (grains)", fr: "Vrac, solide, particules granuleuses (grains)", category: 'bulk' },
  { code: "VS", tr: "Dökme, ferraille", fr: "Vrac, ferraille", category: 'bulk' },
  { code: "VY", tr: "Dökme, solide, İnce Tane (poudres)", fr: "Vrac, solide, particules fines (poudres)", category: 'bulk' },
  { code: "BB", tr: "Bobin", fr: "Bobine", category: 'reel' },
  { code: "RO", tr: "Rouleau", fr: "Rouleau", category: 'reel' },
  { code: "BD", tr: "Tahta (board)", fr: "Planche (board)", category: 'piece' },
  { code: "BY", tr: "Tahtas (boards) en ballot, botte, faisceau", fr: "Planches (boards) en ballot, botte, faisceau", category: 'piece' },
  { code: "IN", tr: "Külçe", fr: "Lingot", category: 'piece' },
  { code: "IZ", tr: "Külçeler en ballot, botte, faisceau", fr: "Lingots en ballot, botte, faisceau", category: 'piece' },
  { code: "PG", tr: "Levha", fr: "Plaque", category: 'piece' },
  { code: "PN", tr: "Tahta (plank)", fr: "Planche (plank)", category: 'piece' },
  { code: "PY", tr: "Levhalar en ballot, botte, faisceau", fr: "Plaques en ballot, botte, faisceau", category: 'piece' },
  { code: "PZ", tr: "Tahtas (planks) en ballot, botte, faisceau", fr: "Planches (planks) en ballot, botte, faisceau", category: 'piece' },
  { code: "6H", tr: "Kompozit Ambalaj, Plastik Kap", fr: "Emballage composite, récipient en plastique", category: 'other' },
  { code: "6P", tr: "Kompozit Ambalaj, Cam Kap", fr: "Emballage composite, récipient en verre", category: 'other' },
  { code: "8C", tr: "Ahşap Balya", fr: "Ballot, en bois", category: 'other' },
  { code: "AC", tr: "Kağıt Kap", fr: "Réceptacle en papier", category: 'other' },
  { code: "AD", tr: "Ahşap Kap", fr: "Réceptacle en bois", category: 'other' },
  { code: "AE", tr: "Aerosol", fr: "Aérosol", category: 'other' },
  { code: "AG", tr: "Palet, Termal Büzüşmeli Folyolu", fr: "Pallette, housse thermorétractable", category: 'other' },
  { code: "AI", tr: "Çift Kabuklu Blister", fr: "Blister double coque", category: 'other' },
  { code: "AJ", tr: "Külah", fr: "Cornet", category: 'other' },
  { code: "AL", tr: "Bilye", fr: "Bille", category: 'other' },
  { code: "AM", tr: "Korumasız Ampul", fr: "Ampoule non protégée", category: 'other' },
  { code: "AP", tr: "Korumalı Ampul", fr: "Ampoule protégée", category: 'other' },
  { code: "AT", tr: "Atomizör", fr: "Atomiseur", category: 'other' },
  { code: "AV", tr: "Kapsül", fr: "Capsule", category: 'other' },
  { code: "B4", tr: "Kayış", fr: "Courroie", category: 'other' },
  { code: "BA", tr: "Fıçı", fr: "Baril", category: 'other' },
  { code: "BE", tr: "Balya", fr: "Ballot", category: 'other' },
  { code: "BF", tr: "Korumasız Balon", fr: "Ballon non protégé", category: 'other' },
  { code: "BH", tr: "Demet", fr: "Bouquet", category: 'other' },
  { code: "BI", tr: "Tekne", fr: "Bac", category: 'other' },
  { code: "BJ", tr: "Kova", fr: "Baquet (bucket)", category: 'other' },
  { code: "BK", tr: "Sepet", fr: "Corbeille", category: 'other' },
  { code: "BL", tr: "Sıkıştırılmış Balya", fr: "Balle comprimée", category: 'other' },
  { code: "BM", tr: "Leğen", fr: "Cuvette", category: 'other' },
  { code: "BN", tr: "Sıkıştırılmamış Balya", fr: "Balle non comprimée", category: 'other' },
  { code: "BP", tr: "Korumalı Balon", fr: "Ballon protégé", category: 'other' },
  { code: "BR", tr: "Çubuk", fr: "Barre", category: 'other' },
  { code: "BT", tr: "Parça", fr: "Pièce", category: 'other' },
  { code: "BU", tr: "Büyük Fıçı", fr: "Barrique", category: 'other' },
  { code: "BZ", tr: "Demet Halinde Çubuk", fr: "Barres en ballot, botte, faisceau", category: 'other' },
  { code: "CE", tr: "Sepet (Manne) Sepet", fr: "Manne", category: 'other' },
  { code: "CF", tr: "Asker Sandığı Sandık", fr: "Cantine", category: 'other' },
  { code: "CG", tr: "Kafes", fr: "Cage", category: 'other' },
  { code: "CH", tr: "Sandık", fr: "Coffre", category: 'other' },
  { code: "CJ", tr: "Tabut", fr: "Cercueil", category: 'other' },
  { code: "CK", tr: "Büyük Tahta Fıçı", fr: "Foudre", category: 'other' },
  { code: "CL", tr: "Halat Yumağı", fr: "Glène", category: 'other' },
  { code: "CM", tr: "Kart", fr: "Carte (card)", category: 'other' },
  { code: "CO", tr: "Korumasız Damacana", fr: "Bonbonne non protégée", category: 'other' },
  { code: "CP", tr: "Korumalı Damacana", fr: "Bonbonne protégée", category: 'other' },
  { code: "CQ", tr: "Kartuş", fr: "Cartouche", category: 'other' },
  { code: "CR", tr: "Çerçeve", fr: "Cadre", category: 'other' },
  { code: "CU", tr: "Kupa", fr: "Coupe", category: 'other' },
  { code: "CV", tr: "Kılıf", fr: "Étui", category: 'other' },
  { code: "CW", tr: "Rulo", fr: "Roll", category: 'other' },
  { code: "CY", tr: "Silindir", fr: "Cylindre", category: 'other' },
  { code: "CZ", tr: "Branda", fr: "Bâche", category: 'other' },
  { code: "DG", tr: "CHEP Kafesi", fr: "Cage CHEP (Commonwealth Handling Equipment Pool)", category: 'other' },
  { code: "DJ", tr: "Korumasız Dama Şişesi", fr: "Dame-jeanne non protégée", category: 'other' },
  { code: "DN", tr: "Aerosol Üreteci", fr: "Générateur aérosol", category: 'other' },
  { code: "DP", tr: "Korumalı Dama Şişesi", fr: "Dame-jeanne protégée", category: 'other' },
  { code: "DS", tr: "Tepsi Plastikten, Tek Kat, Kapaksız", fr: "Plateau en plastique, un niveau, sans couvercle", category: 'other' },
  { code: "DT", tr: "Tepsi Ahşaptan, Tek Kat, Kapaksız", fr: "Plateau en bois, un niveau, sans couvercle", category: 'other' },
  { code: "DU", tr: "Polistiren Tepsi, Tek Kat, Kapaksız", fr: "Plateau en polystyrène, un niveau, sans couvercle", category: 'other' },
  { code: "DW", tr: "Tepsi Plastikten, Çift Kat, Kapaksız", fr: "Plateau en plastique, deux niveaux, sans couvercle", category: 'other' },
  { code: "DX", tr: "Tepsi Ahşaptan, Çift Kat, Kapaksız", fr: "Plateau en bois, deux niveaux, sans couvercle", category: 'other' },
  { code: "EI", tr: "İzotermik Tekne", fr: "Bac isotherme", category: 'other' },
  { code: "EN", tr: "Zarf", fr: "Enveloppe", category: 'other' },
  { code: "FB", tr: "Flexibag (Esnek Çuval)", fr: "Flexibag", category: 'other' },
  { code: "FD", tr: "Kafes Kasası", fr: "Harasse", category: 'other' },
  { code: "FE", tr: "Flexitank (Esnek Tank)", fr: "Flexitank", category: 'other' },
  { code: "FI", tr: "Büyük Varil", fr: "Futaille", category: 'other' },
  { code: "FO", tr: "Mücevher Kutusu", fr: "Coffret", category: 'other' },
  { code: "FP", tr: "Filmpack", fr: "Filmpack", category: 'other' },
  { code: "FR", tr: "Şasi", fr: "Châssis", category: 'other' },
  { code: "FT", tr: "Gıda Kabı (Foodtainer)", fr: "Barquette pour aliments (foodtainer)", category: 'other' },
  { code: "FW", tr: "Düz Kart («flatbed»)", fr: "Carte à plat («flatbed»)", category: 'other' },
  { code: "GI", tr: "Kiriş", fr: "Poutrelle", category: 'other' },
  { code: "GR", tr: "Cam Kap", fr: "Réceptacle en verre", category: 'other' },
  { code: "GU", tr: "Düz İstifli Ürün Tepsisi", fr: "Plateau contenant des articles empilés à plat", category: 'other' },
  { code: "GZ", tr: "Demet Halinde Kiriş", fr: "Poutrelles en ballot, botte, faisceau", category: 'other' },
  { code: "HA", tr: "Kulplu Sepet, Plastik", fr: "Corbeille avec anse, en plastique", category: 'other' },
  { code: "HB", tr: "Kulplu Sepet, Ahşap", fr: "Corbeille avec anse, en bois", category: 'other' },
  { code: "HN", tr: "Kanca («hanger»)", fr: "Crochet («hanger»)", category: 'other' },
  { code: "HR", tr: "Sepet", fr: "Panier", category: 'other' },
  { code: "IA", tr: "Sunum Ambalajı, Ahşap", fr: "Emballage de présentation, en bois", category: 'other' },
  { code: "IC", tr: "Sunum Ambalajı, Plastik", fr: "Emballage de présentation, en plastique", category: 'other' },
  { code: "ID", tr: "Sunum Ambalajı, Metal", fr: "Emballage de présentation, en métal", category: 'other' },
  { code: "IE", tr: "Pencereli Ambalaj", fr: "Emballage à fenêtre", category: 'other' },
  { code: "IF", tr: "Tübüler Ambalaj", fr: "Emballage tubulaire", category: 'other' },
  { code: "IG", tr: "Kağıt Sarımlı Ambalaj", fr: "Emballage, enrobé dans du papier", category: 'other' },
  { code: "IL", tr: "Sert İstiflenebilir Kapaklı Tepsi (CEN TS 14482)", fr: "Plateau rigide, empilable, à couvercle (CEN TS 14482:2002)", category: 'other' },
  { code: "JG", tr: "Sürahi", fr: "Cruche", category: 'other' },
  { code: "JR", tr: "Küp", fr: "Jarre", category: 'other' },
  { code: "KG", tr: "Küçük Fıçı", fr: "Tonnelet", category: 'other' },
  { code: "LE", tr: "Bagaj", fr: "Bagage", category: 'other' },
  { code: "LG", tr: "Tomruk", fr: "Grume", category: 'other' },
  { code: "LT", tr: "Lot", fr: "Lot", category: 'other' },
  { code: "LU", tr: "Case Ahşaptan («lug»)", fr: "Case en bois («lug»)", category: 'other' },
  { code: "LV", tr: "Çerçeve (liftvan)", fr: "Cadre (liftvan)", category: 'other' },
  { code: "LZ", tr: "Demet Halinde Tomruk", fr: "Grumes en ballot, botte, faisceau", category: 'other' },
  { code: "MR", tr: "Metal Kap", fr: "Réceptacle en métal", category: 'other' },
  { code: "MT", tr: "Hasır", fr: "Natte", category: 'other' },
  { code: "MW", tr: "Réceptable, enrobage Plastikten", fr: "Réceptable, enrobage en plastique", category: 'other' },
  { code: "NA", tr: "Bilgi Yok", fr: "Pas disponible", category: 'other' },
  { code: "NE", tr: "Ambalajsız Mal", fr: "Marchandises non emballées", category: 'other' },
  { code: "NF", tr: "Ambalajsız Tek Birim", fr: "Non emballé ni conditionné, une seule unité", category: 'other' },
  { code: "NG", tr: "Ambalajsız Çoklu Birim", fr: "Non emballé ni conditionné, plusieurs unités", category: 'other' },
  { code: "NT", tr: "Ağ Torba", fr: "Filet", category: 'other' },
  { code: "NU", tr: "Ağ Torba tübüler, Plastikten", fr: "Filet tubulaire, en plastique", category: 'other' },
  { code: "NV", tr: "Ağ Torba tübüler, en textile", fr: "Filet tubulaire, en textile", category: 'other' },
  { code: "OF", tr: "Plate- forme, poids et dimension non spécifiés", fr: "Plate- forme, poids et dimension non spécifiés", category: 'other' },
  { code: "OK", tr: "Bloc", fr: "Bloc", category: 'other' },
  { code: "OT", tr: "Octabin", fr: "Octabin", category: 'other' },
  { code: "P2", tr: "Leğen («pan»)", fr: "Cuvette («pan»)", category: 'other' },
  { code: "PA", tr: "Paket", fr: "Paquet", category: 'other' },
  { code: "PC", tr: "Colis (parcel)", fr: "Colis (parcel)", category: 'other' },
  { code: "PF", tr: "Stylo, stylet (pen)", fr: "Stylo, stylet (pen)", category: 'other' },
  { code: "PH", tr: "Sürahi", fr: "Pichet", category: 'other' },
  { code: "PI", tr: "Tuyau", fr: "Tuyau", category: 'other' },
  { code: "PJ", tr: "Flein", fr: "Flein", category: 'other' },
  { code: "PK", tr: "Colis (package)", fr: "Colis (package)", category: 'other' },
  { code: "PL", tr: "Seau", fr: "Seau", category: 'other' },
  { code: "PP", tr: "Parça", fr: "Pièce", category: 'other' },
  { code: "PR", tr: "Plastik Kap", fr: "Réceptacle en plastique", category: 'other' },
  { code: "PU", tr: "Tepsi", fr: "Plateau", category: 'other' },
  { code: "PV", tr: "Tuyaux en ballot, botte, faisceau", fr: "Tuyaux en ballot, botte, faisceau", category: 'other' },
  { code: "RD", tr: "Tige", fr: "Tige", category: 'other' },
  { code: "RG", tr: "Bague", fr: "Bague", category: 'other' },
  { code: "RJ", tr: "Penderie mobile", fr: "Penderie mobile", category: 'other' },
  { code: "RK", tr: "Rayonnage (rack)", fr: "Rayonnage (rack)", category: 'other' },
  { code: "RL", tr: "Touret", fr: "Touret", category: 'other' },
  { code: "RT", tr: "Ağ Torba à fruits", fr: "Filet à fruits", category: 'other' },
  { code: "RZ", tr: "Tiges en ballot, botte, faisceau", fr: "Tiges en ballot, botte, faisceau", category: 'other' },
  { code: "SB", tr: "Feuille calandrée", fr: "Feuille calandrée", category: 'other' },
  { code: "SD", tr: "Dévidoir", fr: "Dévidoir", category: 'other' },
  { code: "SE", tr: "Sandık de marin", fr: "Coffre de marin", category: 'other' },
  { code: "SI", tr: "Luge (skid)", fr: "Luge (skid)", category: 'other' },
  { code: "SM", tr: "Tôle", fr: "Tôle", category: 'other' },
  { code: "SO", tr: "Dévidoir (spool)", fr: "Dévidoir (spool)", category: 'other' },
  { code: "SP", tr: "Feuille, emrobage Plastikten", fr: "Feuille, emrobage en plastique", category: 'other' },
  { code: "SS", tr: "Tekne Çelikten", fr: "Bac en acier", category: 'other' },
  { code: "ST", tr: "Feuille", fr: "Feuille", category: 'other' },
  { code: "SU", tr: "Valise", fr: "Valise", category: 'other' },
  { code: "SV", tr: "Zarf Çelikten", fr: "Enveloppe en acier", category: 'other' },
  { code: "SW", tr: "Termal Büzüşmeli Ambalaj", fr: "Emballage thermorétractable", category: 'other' },
  { code: "SX", tr: "Assortiment (set)", fr: "Assortiment (set)", category: 'other' },
  { code: "SY", tr: "Manchon", fr: "Manchon", category: 'other' },
  { code: "SZ", tr: "Tôles en ballot, botte, faisceau", fr: "Tôles en ballot, botte, faisceau", category: 'other' },
  { code: "T1", tr: "Tablette", fr: "Tablette", category: 'other' },
  { code: "TB", tr: "Kova (tub)", fr: "Baquet (tub)", category: 'other' },
  { code: "TE", tr: "Pneumatique", fr: "Pneumatique", category: 'other' },
  { code: "TI", tr: "Feuillette", fr: "Feuillette", category: 'other' },
  { code: "TK", tr: "Citerne dörtgen", fr: "Citerne rectangulaire", category: 'other' },
  { code: "TL", tr: "Kova ile couvercle", fr: "Baquet avec couvercle", category: 'other' },
  { code: "TO", tr: "Tonne", fr: "Tonne", category: 'other' },
  { code: "TR", tr: "Malle", fr: "Malle", category: 'other' },
  { code: "TS", tr: "Faisceau", fr: "Faisceau", category: 'other' },
  { code: "TY", tr: "Citerne silindirik", fr: "Citerne cylindrique", category: 'other' },
  { code: "UC", tr: "Libre (animal)", fr: "Libre (animal)", category: 'other' },
  { code: "UN", tr: "Unité", fr: "Unité", category: 'other' },
  { code: "VA", tr: "Cuve", fr: "Cuve", category: 'other' },
  { code: "VI", tr: "Fiole", fr: "Fiole", category: 'other' },
  { code: "VK", tr: "Vanpack", fr: "Vanpack", category: 'other' },
  { code: "VN", tr: "Véhicule", fr: "Véhicule", category: 'other' },
  { code: "VP", tr: "Vakum Ambalajı", fr: "Emballage sous vide", category: 'other' },
  { code: "WB", tr: "Damacana clissée", fr: "Bonbonne clissée", category: 'other' },
  { code: "YV", tr: "Kompozit Ambalaj, Cam Kap ile panier extérieur en osier", fr: "Emballage composite, récipient en verre avec panier extérieur en osier", category: 'other' },
  { code: "YY", tr: "Kompozit Ambalaj, Cam Kap ile emballage extérieur Plastikten expansé", fr: "Emballage composite, récipient en verre avec emballage extérieur en plastique expansé", category: 'other' },
  { code: "YZ", tr: "Kompozit Ambalaj, Cam Kap ile emballage extérieur Sert Plastikten", fr: "Emballage composite, récipient en verre avec emballage extérieur en plastique rigide", category: 'other' },
  { code: "ZZ", tr: "Genel Tanım", fr: "Définition commune", category: 'other' },
]

export function findPackageType(code?: string | null): PackageTypeInfo | undefined {
  if (!code) return undefined
  return PACKAGE_TYPES.find((p) => p.code === code.trim().toUpperCase())
}
